In [1]:
import pandas as pd

In [2]:
filled_frame = pd.read_csv('../csv_files/cleaned_gapminder.csv')

In [3]:
# Creating copy of original dataframe
copy_filled_frame = filled_frame.copy()

In [4]:
column_names = [col.strip() for col in copy_filled_frame]       

# Normalizing = "making range of each column same"
# Applying formula of normalizing value on each cell of each column 
for column in column_names:
    if column != 'Country':
        exact_column = copy_filled_frame[column]
        maxi = exact_column.max()
        mini = exact_column.min()
        for index, value in exact_column.iteritems():
            normalize_value = (value - mini)/(maxi - mini)
            copy_filled_frame.at[index, column] = normalize_value

copy_filled_frame.head()

,Country,AgriLand,ChildrenPerWoman,DemocracyScore,Exports,FemaleParticipation,ForestArea,GDPpercapita,HealthSpendPerPerson,Hightotechnologyexports,...,LifeExpectancy,LiteracyRateAdult,LIteracyRateYouth,Populationdensity,ElectricityPerPerson,Taxrevenue,Tradebalance,Trafficdeaths,Urbanpopulationgrowth,YearlyCO2emission
0,Afghanistan,0.637246,0.908026,0.000000,0.072753,0.306483,0.001668,0.000000,0.000394,0.000000,...,0.329042,0.000000,0.000000,0.000544,0.000000,0.088789,0.568214,0.292784,0.599599,0.000013
1,Albania,0.458688,0.718632,0.050000,0.078141,0.742471,0.000950,0.010674,0.007983,0.018374,...,0.657844,0.961625,0.988313,0.001862,0.047557,0.226831,0.538184,0.104722,0.515212,0.000053
2,Algeria,0.191968,0.905303,0.204167,0.124233,0.303071,0.001951,0.015773,0.011205,0.020664,...,0.511616,0.000000,0.000000,0.000162,0.021643,0.768895,0.639898,0.154219,0.586622,0.000553
3,AmericanSamoa,0.228145,0.000000,0.500000,0.000000,0.000000,0.000022,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.004137,0.000000,0.000000,0.633980,0.000000,0.554429,0.000000
4,Andorra,0.487357,0.000000,0.500000,0.000000,0.000000,0.000020,0.160796,0.210638,0.234879,...,0.000000,0.000000,0.000000,0.000653,0.000000,0.000000,0.633980,0.107312,0.515486,0.000073

In [5]:
# Combining multiple rows into single row for each country by taking average(mean) of each column
grouped = copy_filled_frame.groupby(by='Country')
grouped = grouped.mean()

# Creating new column of same size and filling it with zero
grouped['total_pts'] = [0 for num in range(grouped.shape[0])]

# Adding specific columns and saving result into new column created before
for col in ['AgriLand', 'DemocracyScore', 'Exports', 'FemaleParticipation', 'ForestArea', 'GDPpercapita', 'HealthSpendPerPerson', 'Hightotechnologyexports', 'IncomePerPerson', 'Internetusers', 'LifeExpectancy', 'LiteracyRateAdult', 'LIteracyRateYouth', 'ElectricityPerPerson', 'Taxrevenue', 'Tradebalance', 'Urbanpopulationgrowth']:
    grouped['total_pts'] += grouped[col]
# Subtracting specific columns from new column created before
for col in ['Imports', 'Incomeshareofrichest10pct', 'ChildrenPerWoman', 'Trafficdeaths', 'Infantmortality', 'Inflation', 'Populationdensity', 'YearlyCO2emission']:
    grouped['total_pts'] -= grouped[col]

# Sorting column highest to lowest value for ranking 
final = grouped['total_pts'].sort_values(ascending = False).to_frame()
final['Country'] = final.index
final.drop(columns=['total_pts'], inplace=True)
# Creating new column of Ranking
final['Rank'] = [num+1 for num in range(grouped.shape[0])]

In [6]:
# final.to_csv('../csv_files/ranked_gapminder.csv', index=False)